name: continious integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'v*/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker images 7.2
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=dannecron/php-for-dev:7.2 --build-arg BUILDKIT_INLINE_CACHE=1 --tag=localhost/php-for-dev:7.2 ./v7.2
          docker run --rm localhost/php-for-dev:7.2 php -v
          docker tag localhost/php-for-dev:7.2 dannecron/php-for-dev:7.2
          echo "Done"

      - name: Build the Docker images 7.3
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=dannecron/php-for-dev:7.3 --build-arg BUILDKIT_INLINE_CACHE=1 --tag=localhost/php-for-dev:7.3 ./v7.3
          docker run --rm localhost/php-for-dev:7.3 php -v
          docker tag localhost/php-for-dev:7.3 dannecron/php-for-dev:7.3
          echo "Done"

      - name: Build the Docker images 7.4
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=dannecron/php-for-dev:7.4 --build-arg BUILDKIT_INLINE_CACHE=1 --tag=localhost/php-for-dev:7.4 ./v7.4
          docker run --rm localhost/php-for-dev:7.4 php -v
          docker tag localhost/php-for-dev:7.4 dannecron/php-for-dev:7.4
          docker tag localhost/php-for-dev:7.4 dannecron/php-for-dev:latest
          echo "Done"

      - name: Build the Docker images 8.0
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=dannecron/php-for-dev:8.0 --build-arg BUILDKIT_INLINE_CACHE=1 --tag=localhost/php-for-dev:8.0 ./v8.0
          docker run --rm localhost/php-for-dev:8.0 php -v
          docker tag localhost/php-for-dev:8.0 dannecron/php-for-dev:8.0
          echo "Done"
      - name: Build the Docker images 8.1
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=dannecron/php-for-dev:8.1 --build-arg BUILDKIT_INLINE_CACHE=1 --tag=localhost/php-for-dev:8.1 ./v8.1
          docker run --rm localhost/php-for-dev:8.1 php -v
          docker tag localhost/php-for-dev:8.1 dannecron/php-for-dev:8.1
          echo "Done"

      - name: push 7.2 image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:7.2

      - name: push 7.3 image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:7.3

      - name: push 7.4 image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:7.4

      - name: push 8.0 image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:8.0

      - name: push 8.1 image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:8.1

      - name: push latest image to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push dannecron/php-for-dev:latest
